=pod

=head1 NAME

Package::Transporter::Generator::Auto_Autoload - strip subroutines while loading a package

=head1 SYNOPSIS

	use strict;
	use Package::Transporter sub{eval shift}, sub {
		my $generator = $_[0]->create_generator('::Auto_Autoload', 'URI');
		$_[0]->register_potential($generator, 'FOR_ANY');
	};
	
	use URI;
	my $uri = URI->new('http:://www.perl.org');
	
	exit(0);

=head1 DESCRIPTION

Strip subroutines from a package on-the-fly and keep them for autoloading. Like a source filter. This module hardly has a practical value. It is not meant to replace

=head1 ANYTHING ELSE

Please see the documentation of the upstream package L<Package::Transporter>.

=cut
