=pod

=head1 NAME

Package::Transporter::Generator::Require_Customized - Include customized file content

=head1 SYNOPSIS

	use lib '.'; # allows the .pl files to be read via require()
	
	use Package::Transporter sub{eval shift}, sub {
		my $generator = $_[0]->create_generator('::Require_Customized',
			'GREET_TO' => 'Mundo');
		$_[0]->register_potential($generator, 'FOR_ANY',
			'require_customized');
	};
	
	# This is not taint-safe!
	require_customized('hello_world.pl');
	
	exit(0);
	
=head1 DESCRIPTION

Load the content of a file, appy search & replace according to a configurable hash and eval the result.

=head1 ANYTHING ELSE

Please see the documentation of the upstream package L<Package::Transporter>.

=cut
