=pod

=head1 NAME

Package::Transporter::Generator::Set_Accessors_Demo - automatic set-style accessors

=head1 SYNOPSIS

	use strict;
	
	use Package::Transporter sub{eval shift}, sub {
		$_[0]->register_potential('::Set_Accessors_Demo', 'FOR_ANY', 'set_');
	};
	
	my $obj = bless( {}, 'main');
	$obj->set_world(1);
	
	use Data::Dumper;
	print STDERR Dumper($obj);
	
	exit(0);
	

=head1 DESCRIPTION

The above example enables set-style accessors (a thin layer of subroutines to manage attributes) for objects globally. While it might be useful in specific situations, it's a bug breeding plant in general. Use constants functions instead (see perlsub and L<Package::Transporter>).

=head1 ANYTHING ELSE

Please see the documentation of the upstream package L<Package::Transporter>.

=cut
