=pod

=head1 NAME

Package::Transporter::Generator::Constant_Function::Flatened - generate constant functions with manually set flatened values

=head1 SYNOPSIS

	package Parent_Class;
	use Package::Transporter sub{eval shift}, sub {
		$_[0]->register_drain('::Flatened', 'FOR_FAMILY', 'ATB_', 
			'NAME' => 'Apple',
			'STOCK' => 71,
			'PRICE' => 9.99);
	};
	
	package Child_Class;
	BEGIN {our @ISA = ('Parent_Class')}; # more like 'use parent ...'
	use Package::Transporter sub{eval shift}, sub {
		$_[0]->register_drain('::Flatened', 'FOR_SELF',
			'ATB_', 'SALE' => 'yes');
	};
	
	print STDOUT 'ATB_PRICE=', ATB_PRICE, "\n";
	print STDOUT 'ATB_SALE=', ATB_SALE, "\n";
	exit(0);

=head1 DESCRIPTION

Enumeration is restarted in each affected package. (Caution: this is implicit drain.)

=head1 ANYTHING ELSE

Please see the documentation of the upstream package L<Package::Transporter>.

=cut
