=pod

=head1 NAME

Package::Transporter::Generator::Universal::Automatic_Require - Attempt an 'require MODULE' for a missing MODULE::subroutine

=head1 SYNOPSIS

	use Package::Transporter sub{eval shift}, sub {
		$_[0]->register_potential('::Automatic_Require', 'FOR_ANY');
	};
	
	print CGI->h1->('Hello World.'), "\n";
	exit(0);

=head1 DESCRIPTION

Guesses the module name by looking at $_[0] (class name) for method calls on class names.

=head1 ANYTHING ELSE

Please see the documentation of the upstream package L<Package::Transporter>.

=cut
